services:
  db:
    image: mariadb:11
    container_name: fastapi_mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    networks:
      - api-network
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u$$MARIADB_USER -p$$MARIADB_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - api-network

volumes:
  mariadb_data:

networks:
  api-network:
    driver: bridge
